name: sports_books
description: Sports Books web app (Clean Architecture)
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  google_sign_in: 6.2.1    # ← PIN cứng 6.2.1 (không dùng ^)
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
